### ISSUE TITLE
/node_modules/@paulcbetts/system-idle-time/build/Release/system_idle_time.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 51. This version of Node.js requires NODE_MODULE_VERSION 53. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or`npm install`).

### ISSUE THREAD

**Issue by AnjaneyuluBatta505** [paulcbetts/node-system-idle-time#10]
Uncaught Error: The module '../node_modules/@paulcbetts/system-idle-time/build/Release/system_idle_time.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/home/anjaneyulu/company/gitlab/microtrack-client/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/anjaneyulu/company/gitlab/microtrack-client/node_modules/@paulcbetts/system-idle-time/addon.js:1:192)
    at Object.<anonymous> (/home/anjaneyulu/company/gitlab/microtrack-client/node_modules/@paulcbetts/system-idle-time/addon.js:3:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

I tried  `npm rebuild` or`npm install`  but it didn't work.

**Comment by paulcbetts** [comment]
Hi you should read about how to use electron-rebuild (ideally by just switching to electron-forge), and how to recompile native modules for Electron

**Comment by AnjaneyuluBatta505** [comment]
I downgraded my `node` and `npm` version it worked for me
