### ISSUE TITLE
fatal error LNK1107: invalid or corrupt file: cannot read at 0x186E76

### ISSUE THREAD

**Issue by AhmadIbrahiim** [paulcbetts/node-system-idle-time#13]
**NPM Version :** 5.6.0
 **OS:** Windows 10
 i used to get : 
`C:\Users\Ahmed\.node-gyp\iojs-1.2.1\x64\iojs.lib : fatal error LNK1107: invalid or corrupt file: cannot read at 0x186E76 [D:\Mine\Projects (NON-Bot)\Rocket.Chat.Electron\node_modules\@paulcbetts\system-idle-time\build\system_idle_time.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299`

Any Possible solution ?

**Comment by cumajkeee** [comment]
Hi @paulcbetts I run into same issue with electron v3.beta4? any solution?
