### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by nickyhajal** [paulcbetts/node-system-idle-time#2]
I've been using this in a project and after updating to Electron 1.x I'm getting the following error: 

```
App threw an error during load
Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/nicky/project/node_modules/node-system-idle-time/node_modules/bindings/bindings.js:77:44)
```

Any thoughts on how to resolve this?

**Comment by paulcbetts** [comment]
Need to `electron-rebuild` when you bump major versions
