### ISSUE TITLE
Error building on windows

### ISSUE THREAD

**Issue by bhavyaw** [paulcbetts/node-system-idle-time#4]
I tried to build this ( using nw-gyp ) on window and got this error : 

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
**C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\
Users\Bhavya\Documents\projects\productivityOne\desktopApp\addOns\systemIdleTime\node-system-idle-time\build\system_idle_time.vcxproj]**
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Bhavya\AppData\Roaming\npm\node_modules\nw-gyp\lib\build.js:294:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Bhavya\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "--target=0.14
.3" "rebuild"
gyp ERR! cwd C:\Users\Bhavya\Documents\projects\productivityOne\desktopApp\addOns\systemIdleTime\node-system-idle-time
gyp ERR! node -v v4.5.0
gyp ERR! nw-gyp -v v3.4.0
gyp ERR! not ok

**Comment by bhavyaw** [comment]
I guess this is some error related to the required build tools / dependencies on windows as I am not able to build other addons as well. Therefore, I am closing this one.
